version: '3.9'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data   # trwałość activities.json
    environment:
      - NODE_ENV=production
    restart: unless-stopped
